spring.application.name=skyshield
spring.datasource.url=jdbc:h2:mem:skyshield;DB_CLOSE_DELAY=-1
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.error.include-message=always
server.port=${PORT:8080}
